spring:
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&characterEncoding=utf8&useUnicode=true
  application:
    name: shop-service
  data:
    redis:
      repositories:
        enabled: false